FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy dependencies
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 5003

# Run the app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5003", "--reload"]
